### ISSUE TITLE
Broken links in GSoC summary post

### ISSUE THREAD

**Issue by kandersolar** [AdamRJensen/adamrjensen.github.io#29]
Several links in [Summary of Google Summer of Code with pvlib](https://predictablysunny.com/posts/gsoc_project_summary/) are broken/out of date, for example: https://pvlib-python.readthedocs.io/en/latest/generated/pvlib.iotools.get_bsrn.html

**Comment by AdamRJensen** [comment]
More importantly, the link to my mentor was broken! Maybe that's your true secret agenda 😉
