### ISSUE TITLE
triple backticks issue on `author` post metadata

### ISSUE THREAD

**Issue by kanderso-nrel** [AdamRJensen/adamrjensen.github.io#5]
Some posts show backticks after the author name, for example:

![image](https://user-images.githubusercontent.com/57452607/188678531-d9400b4e-356c-487e-8419-2c8ef4bd5a1a.png)

I suppose it is due to putting the closing backticks on the same line as the author metadata instead of the following line, i.e.

```
    ```{post} 12 Feb 2022
    :tags: solar, open science
    :author: Adam R. Jensen```
```
versus
```
    ```{post} 2022-02-22
    :tags: open science
    :author: Adam R. Jensen
    ```
```

**Comment by AdamRJensen** [comment]
Thank you @kanderso-nrel 🙇
